# Generated by Django 3.0.4 on 2020-04-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('client_type', models.CharField(max_length=50)),
                ('client_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model_number', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('cell_technology', models.CharField(max_length=50)),
                ('cell_manufacturer', models.CharField(max_length=50)),
                ('number_of_cells', models.IntegerField()),
                ('number_of_cells_in_series', models.IntegerField()),
                ('number_of_series_strings', models.CharField(max_length=50)),
                ('number_of_diodes', models.IntegerField()),
                ('product_length', models.CharField(max_length=50)),
                ('product_width', models.CharField(max_length=50)),
                ('product_weight', models.CharField(max_length=50)),
                ('superstate_type', models.CharField(max_length=50)),
                ('superstate_manufacturer', models.CharField(max_length=50)),
                ('substrate_type', models.CharField(max_length=50)),
                ('substrate_manufacturer', models.CharField(max_length=50)),
                ('frame_type', models.CharField(max_length=50)),
                ('frame_adhesive', models.CharField(max_length=50)),
                ('encapsulate_type', models.CharField(max_length=50)),
                ('encapsulant_manufacturer', models.CharField(max_length=50)),
                ('junction_box_type', models.CharField(max_length=50)),
                ('junction_box_manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Sequence',
            fields=[
                ('sequence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Standard',
            fields=[
                ('standard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('standard_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('office_phone', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('is_fi_required', models.BooleanField()),
                ('fi_frequency', models.CharField(max_length=50)),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_system_voltage', models.CharField(max_length=50)),
                ('voc', models.CharField(max_length=50)),
                ('isc', models.CharField(max_length=50)),
                ('vmp', models.CharField(max_length=50)),
                ('imp', models.CharField(max_length=50)),
                ('pmp', models.CharField(max_length=50)),
                ('ff', models.CharField(max_length=50)),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('sequence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('fax_number', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_number', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('report_number', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Standard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
