# Generated by Django 3.0.4 on 2020-04-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Performance',
            new_name='Performance_data',
        ),
    ]
