# Generated by Django 3.0.4 on 2020-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200427_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='report_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='fax_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance_data',
            name='ff',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance_data',
            name='imp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance_data',
            name='isc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance_data',
            name='max_system_voltage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance_data',
            name='pmp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance_data',
            name='vmp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance_data',
            name='voc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='fi_frequency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='test_standard',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test_standard',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
