# Generated by Django 3.0.4 on 2020-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200427_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cell_manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cell_technology',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='encapsulant_manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='encapsulate_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame_adhesive',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='junction_box_manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='junction_box_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_cells',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_cells_in_series',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_diodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_series_strings',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='substrate_manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='substrate_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='superstate_manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='superstate_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
