# Generated by Django 3.0.4 on 2020-04-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200427_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='model_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='standard_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Standard'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
